import { AttributeKey, ClassDefinition, LineageDefinition, OriginDefinition } from './types';

export const ATTRIBUTE_LABELS: Record<AttributeKey, string> = {
  strength: 'Сила',
  dexterity: 'Ловкость',
  constitution: 'Стойкость',
  intelligence: 'Разум',
  wisdom: 'Восприятие',
  charisma: 'Влияние',
};

export const SKILLS = [
  'Атлетика', 'Акробатика', 'Скрытность', 'Ловкость рук', 'Знание', 'Расследование',
  'Природа', 'Медицина', 'Проницательность', 'Внимание', 'Выживание', 'Убеждение',
  'Обман', 'Запугивание', 'Выступление',
];

export const LINEAGES: LineageDefinition[] = [
  { id: 'human', name: 'Человек', icon: '◈', summary: 'Гибкие, амбициозные и удивительно живучие.', attributeBonuses: { charisma: 1, constitution: 1 }, speed: 9, traits: [{ id: 'adaptable', name: 'Приспособляемость', description: 'Один раз за сцену можно перебросить проваленную проверку сложности 12 или ниже.' }], storyTags: ['human', 'adaptable'] },
  { id: 'aelir', name: 'Эльф', icon: '✦', summary: 'Долгожители с тонкими чувствами, древней памятью и врождённой связью с магией.', attributeBonuses: { dexterity: 2, wisdom: 1 }, speed: 9, traits: [{ id: 'echo-sight', name: 'Эльфийское восприятие', description: 'Замечает магические следы, скрытые детали и отголоски сильных событий.' }], storyTags: ['aelir', 'elf', 'ancient', 'arcane'] },
  { id: 'half-elf', name: 'Полуэльф', icon: '◇', summary: 'Наследник двух народов, умеющий находить своё место между разными мирами.', attributeBonuses: { charisma: 2, wisdom: 1 }, speed: 9, traits: [{ id: 'two-worlds', name: 'Меж двух миров', description: 'Получает преимущество в сценах первого знакомства, дипломатии и культурных конфликтов.' }], storyTags: ['half-elf', 'elf', 'human', 'diplomat'] },
  { id: 'drow', name: 'Дроу', icon: '☾', summary: 'Подземные эльфы, воспитанные среди интриг, вечной тьмы и опасной магии.', attributeBonuses: { dexterity: 2, charisma: 1 }, speed: 9, traits: [{ id: 'deep-sight', name: 'Зрение глубин', description: 'Прекрасно видит во тьме и чувствует присутствие теневой магии.' }], storyTags: ['drow', 'elf', 'underground', 'shadow'] },
  { id: 'stoneborn', name: 'Дворф', icon: '⬟', summary: 'Стойкий народ подземных цитаделей, древних клятв, рун и великого ремесла.', attributeBonuses: { constitution: 2, strength: 1 }, speed: 8, traits: [{ id: 'unyielding', name: 'Дворфийская стойкость', description: 'Преимущество против ядов, истощения и принуждения.' }], storyTags: ['stoneborn', 'dwarf', 'underground', 'craft'] },
  { id: 'smallfolk', name: 'Полурослик', icon: '●', summary: 'Невысокие, храбрые и удивительно удачливые путешественники.', attributeBonuses: { dexterity: 2, charisma: 1 }, speed: 8, traits: [{ id: 'lucky-step', name: 'Удачливый', description: 'Натуральную единицу на проверке можно перебросить один раз за главу.' }], storyTags: ['smallfolk', 'halfling', 'lucky', 'wanderer'] },
  { id: 'gnome', name: 'Гном', icon: '⚙', summary: 'Любознательные мастера иллюзий, механизмов и решений, которые другим не приходят в голову.', attributeBonuses: { intelligence: 2, dexterity: 1 }, speed: 8, traits: [{ id: 'bright-spark', name: 'Искра изобретателя', description: 'Получает преимущество при работе с механизмами, иллюзиями и неизвестными устройствами.' }], storyTags: ['gnome', 'inventor', 'arcane'] },
  { id: 'orc-blooded', name: 'Орк', icon: '▲', summary: 'Могучий наследник кланов, ценящий прямоту, честь и верность своим.', attributeBonuses: { strength: 2, constitution: 1 }, speed: 9, traits: [{ id: 'last-stand', name: 'Последний рубеж', description: 'Один раз за бой остаётся с 1 HP вместо падения до 0.' }], storyTags: ['orc-blooded', 'orc', 'clan', 'warrior'] },
  { id: 'goblin', name: 'Гоблин', icon: '◆', summary: 'Изобретательные выживальщики, быстрые руками и умом.', attributeBonuses: { dexterity: 2, intelligence: 1 }, speed: 9, traits: [{ id: 'scrapper', name: 'Импровизатор', description: 'Может превратить найденный хлам в одноразовый полезный предмет.' }], storyTags: ['goblin', 'inventive', 'outsider'] },
  { id: 'ashborn', name: 'Тифлинг', icon: '♢', summary: 'Потомок существ иных планов, отмеченный рогами, необычной внешностью и адским огнём.', attributeBonuses: { charisma: 2, intelligence: 1 }, speed: 9, traits: [{ id: 'ember-blood', name: 'Адское наследие', description: 'Сопротивление огню и способность зажечь небольшой огонь касанием.' }], storyTags: ['ashborn', 'tiefling', 'outsider', 'infernal'] },
  { id: 'aasimar', name: 'Аасимар', icon: '✺', summary: 'Носитель искры высших сил, чьё присутствие способно вдохновлять и пугать.', attributeBonuses: { charisma: 2, wisdom: 1 }, speed: 9, traits: [{ id: 'celestial-spark', name: 'Небесная искра', description: 'Один раз за главу может исцелить союзника или осветить тьму очищающим сиянием.' }], storyTags: ['aasimar', 'celestial', 'chosen'] },
  { id: 'wildkin', name: 'Зверолюд', icon: '✣', summary: 'Герой со звериными чертами, обострёнными чувствами и сильным природным инстинктом.', attributeBonuses: { wisdom: 2, dexterity: 1 }, speed: 10, traits: [{ id: 'keen-senses', name: 'Чуткие чувства', description: 'Преимущество при поиске следов, засад и скрытых существ.' }], storyTags: ['wildkin', 'beastfolk', 'nature', 'hunter'] },
  { id: 'dragonkin', name: 'Драконорождённый', icon: '⬢', summary: 'Гордый наследник древних драконов, несущий в крови силу одной из стихий.', attributeBonuses: { strength: 2, charisma: 1 }, speed: 9, traits: [{ id: 'breath', name: 'Дыхание предка', description: 'Один раз за бой поражает несколько целей стихийным дыханием.' }], storyTags: ['dragonkin', 'dragonborn', 'ancient', 'noble'] },
  { id: 'returned', name: 'Возвращённый', icon: '☾', summary: 'Те, кого смерть отпустила, но не оставила без метки.', attributeBonuses: { constitution: 1, wisdom: 2 }, speed: 9, traits: [{ id: 'death-memory', name: 'Память смерти', description: 'Чувствует присутствие мёртвых и места трагедий.' }], storyTags: ['returned', 'undead-touched', 'mystery'] },
];

export const CLASSES: ClassDefinition[] = [
  { id: 'vanguard', name: 'Авангард', icon: '⚔', summary: 'Мастер оружия, брони и контроля поля боя.', hitDie: 10, primaryAttributes: ['strength', 'constitution'], savingThrows: ['strength', 'constitution'], skillChoices: 2, availableSkills: ['Атлетика', 'Запугивание', 'Внимание', 'Выживание'], startingEquipment: ['Кольчуга', 'Щит', 'Длинный меч', 'Зелье лечения'], traits: [{ id: 'second-wind', name: 'Второе дыхание', description: 'Один раз за бой восстанавливает 1d8 + уровень HP бонусным действием.' }], storyTags: ['martial', 'leader'] },
  { id: 'shadow', name: 'Тень', icon: '⌁', summary: 'Разведчик, взломщик и специалист по точным ударам.', hitDie: 8, primaryAttributes: ['dexterity', 'intelligence'], savingThrows: ['dexterity', 'intelligence'], skillChoices: 4, availableSkills: ['Акробатика', 'Скрытность', 'Ловкость рук', 'Расследование', 'Обман', 'Внимание'], startingEquipment: ['Кожаная броня', 'Кинжал', 'Короткий меч', 'Инструменты взломщика'], traits: [{ id: 'opening', name: 'Уязвимость', description: 'Раз в ход наносит дополнительный 1d6 урона отвлечённой цели.' }], storyTags: ['stealth', 'criminal'] },
  { id: 'warden', name: 'Следопыт', icon: '➶', summary: 'Охотник, проводник и защитник диких земель.', hitDie: 10, primaryAttributes: ['dexterity', 'wisdom'], savingThrows: ['dexterity', 'wisdom'], skillChoices: 3, availableSkills: ['Природа', 'Внимание', 'Выживание', 'Скрытность', 'Медицина'], startingEquipment: ['Кожаная броня', 'Длинный лук', 'Короткий меч', 'Набор путешественника'], traits: [{ id: 'quarry', name: 'Добыча', description: 'Выбирает цель и получает преимущество при выслеживании и первом ударе.' }], storyTags: ['nature', 'hunter'] },
  { id: 'arcanist', name: 'Арканист', icon: '✧', summary: 'Учёный, меняющий реальность формулами и волей.', hitDie: 6, primaryAttributes: ['intelligence'], savingThrows: ['intelligence', 'wisdom'], skillChoices: 2, availableSkills: ['Знание', 'Расследование', 'Природа', 'Медицина'], startingEquipment: ['Посох', 'Книга формул', 'Дорожная одежда', 'Фокусирующий кристалл'], traits: [{ id: 'spellbook', name: 'Книга формул', description: 'Готовит набор заклинаний после отдыха и может находить новые формулы.' }], storyTags: ['arcane', 'scholar'] },
  { id: 'luminary', name: 'Светоч', icon: '✺', summary: 'Проводник веры, исцеления и оберегающей силы.', hitDie: 8, primaryAttributes: ['wisdom', 'charisma'], savingThrows: ['wisdom', 'charisma'], skillChoices: 2, availableSkills: ['Медицина', 'Проницательность', 'Убеждение', 'Знание'], startingEquipment: ['Чешуйчатая броня', 'Булава', 'Священный символ', 'Зелье лечения'], traits: [{ id: 'radiance', name: 'Живой свет', description: 'Исцеляет союзника или отпугивает порождение тьмы.' }], storyTags: ['divine', 'healer'] },
  { id: 'voice', name: 'Глас', icon: '♪', summary: 'Рассказчик, дипломат и мастер вдохновляющей магии.', hitDie: 8, primaryAttributes: ['charisma', 'dexterity'], savingThrows: ['charisma', 'dexterity'], skillChoices: 3, availableSkills: ['Выступление', 'Убеждение', 'Обман', 'Проницательность', 'Знание'], startingEquipment: ['Рапира', 'Кожаная броня', 'Музыкальный инструмент', 'Дорожный плащ'], traits: [{ id: 'inspiration', name: 'Вдохновение', description: 'Дарует союзнику 1d6 к проверке, атаке или защите.' }], storyTags: ['social', 'artist'] },
  { id: 'bound', name: 'Связанный', icon: '◐', summary: 'Носитель договора с загадочной внешней силой.', hitDie: 8, primaryAttributes: ['charisma'], savingThrows: ['charisma', 'wisdom'], skillChoices: 2, availableSkills: ['Знание', 'Обман', 'Запугивание', 'Расследование'], startingEquipment: ['Ритуальный клинок', 'Кожаная броня', 'Знак покровителя', 'Запечатанное письмо'], traits: [{ id: 'pact', name: 'Договор', description: 'Получает сильный дар и сюжетное обязательство перед покровителем.' }], storyTags: ['pact', 'occult'] },
  { id: 'shaper', name: 'Оборотник', icon: '❧', summary: 'Хранитель круговорота, духов и первозданной природы.', hitDie: 8, primaryAttributes: ['wisdom', 'constitution'], savingThrows: ['wisdom', 'constitution'], skillChoices: 2, availableSkills: ['Природа', 'Медицина', 'Выживание', 'Проницательность'], startingEquipment: ['Кожаная броня', 'Серп', 'Травничий набор', 'Тотем'], traits: [{ id: 'wild-form', name: 'Дикий облик', description: 'Принимает форму знакомого зверя для боя, разведки или путешествия.' }], storyTags: ['nature', 'spirit'] },
  { id: 'adept', name: 'Адепт', icon: '◎', summary: 'Воин дисциплины, скорости и внутренней энергии.', hitDie: 8, primaryAttributes: ['dexterity', 'wisdom'], savingThrows: ['dexterity', 'wisdom'], skillChoices: 2, availableSkills: ['Акробатика', 'Атлетика', 'Проницательность', 'Скрытность'], startingEquipment: ['Боевой посох', 'Метательные ножи', 'Дорожная одежда', 'Чётки'], traits: [{ id: 'flow', name: 'Поток', description: 'После атаки может переместиться или провести быстрый дополнительный удар.' }], storyTags: ['discipline', 'martial'] },
  { id: 'maker', name: 'Механист', icon: '⚙', summary: 'Изобретатель устройств, смесей и магических механизмов.', hitDie: 8, primaryAttributes: ['intelligence', 'dexterity'], savingThrows: ['intelligence', 'constitution'], skillChoices: 3, availableSkills: ['Расследование', 'Знание', 'Ловкость рук', 'Медицина'], startingEquipment: ['Арбалет', 'Кожаная броня', 'Набор механиста', 'Огненная бомба'], traits: [{ id: 'prototype', name: 'Прототип', description: 'Создаёт одно из нескольких устройств и улучшает его между главами.' }], storyTags: ['inventor', 'arcane-tech'] },
];

export const ORIGINS: OriginDefinition[] = [
  { id: 'wanderer', name: 'Странник', icon: '⌖', summary: 'Дороги научили вас находить путь и замечать опасность.', skills: ['Выживание', 'Внимание'], equipment: ['Карта дорог', 'Верёвка'], gold: 8, storyTags: ['wanderer', 'roads'] },
  { id: 'noble', name: 'Наследник', icon: '♜', summary: 'Имя вашей семьи открывает одни двери и закрывает другие.', skills: ['Убеждение', 'Знание'], equipment: ['Перстень рода', 'Парадная одежда'], gold: 25, storyTags: ['noble', 'politics'] },
  { id: 'outlaw', name: 'Изгой', icon: '⌁', summary: 'Вы жили вне закона — по необходимости или убеждению.', skills: ['Скрытность', 'Обман'], equipment: ['Набор отмычек', 'Старый капюшон'], gold: 12, storyTags: ['outlaw', 'underworld'] },
  { id: 'scholar', name: 'Исследователь', icon: '▤', summary: 'Вы посвятили годы книгам, руинам или запретной науке.', skills: ['Знание', 'Расследование'], equipment: ['Полевой дневник', 'Редкая книга'], gold: 10, storyTags: ['scholar', 'mystery'] },
  { id: 'soldier', name: 'Ветеран', icon: '⚑', summary: 'Вы пережили войну и до сих пор помните цену приказов.', skills: ['Атлетика', 'Запугивание'], equipment: ['Знак отряда', 'Трофейный нож'], gold: 14, storyTags: ['soldier', 'war'] },
  { id: 'acolyte', name: 'Послушник', icon: '✥', summary: 'Храм, культ или орден сформировали ваш взгляд на мир.', skills: ['Медицина', 'Проницательность'], equipment: ['Молитвенник', 'Благовония'], gold: 6, storyTags: ['faith', 'order'] },
  { id: 'artisan', name: 'Ремесленник', icon: '⚒', summary: 'Ваше мастерство кормило вас до зова приключений.', skills: ['Ловкость рук', 'Расследование'], equipment: ['Инструменты ремесла', 'Образец работы'], gold: 18, storyTags: ['craft', 'guild'] },
  { id: 'survivor', name: 'Выживший', icon: '☄', summary: 'Катастрофа отняла прежнюю жизнь, но не сломила вас.', skills: ['Выживание', 'Медицина'], equipment: ['Обгоревший талисман', 'Походное одеяло'], gold: 4, storyTags: ['survivor', 'tragedy'] },
];

export function getLineage(id: string) { return LINEAGES.find(item => item.id === id) || LINEAGES[0]; }
export function getClassDefinition(id: string) { return CLASSES.find(item => item.id === id) || CLASSES[0]; }
export function getOrigin(id: string) { return ORIGINS.find(item => item.id === id) || ORIGINS[0]; }
